eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 15000
#ribbon的超时时间
ribbon:
  ReadTimeout: 12000
  ConnectTimeout: 3000
server:
  port: 8763
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.model
spring:
  application:
    name: trade
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/terminal_admin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    druid:
      initial-size: 5
      max-active: 20
      web-stat-filter.enabled: false

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: my_trade
    retry-times-when-send-async-failed: 0
    send-msg-timeout: 10000
    compress-msg-body-over-howmuch: 4096
    max-message-size: 4194304
    retry-another-broker-when-not-store-ok: false
    retry-times-when-send-failed: 2
#  devtools:
#    restart:
#      enabled: true  #设置开启热部署
#      additional-paths: src/main/java #重启目录
#日志配置
log:
  path: /home/log/trade